import { describe, expect, it } from 'vitest';
import { isPlan, planCall, type ToolPlan } from './tools';
const allowed = ['climate.salon', 'cover.volet_salon', 'media_player.salon', 'automation.volets_bas', 'script.bonne_nuit'];
const plan = (name: string, args: Record<string, unknown>) => { const outcome = planCall(name, args, allowed); if (!isPlan(outcome)) throw new Error(outcome.error); return outcome as ToolPlan; };
const failure = (name: string, args: Record<string, unknown>) => { const outcome = planCall(name, args, allowed); return isPlan(outcome) ? '' : outcome.error; };
describe('assistant tool planner', () => {
  it('refuses an entity the household never selected', () => { expect(failure('set_temperature', { entity_id: 'climate.chambre_inventee', temperature: 21 })).toContain('n’est pas pilotable'); expect(failure('set_temperature', { temperature: 21 })).toContain('entity_id'); });
  it('refuses a tool aimed at the wrong kind of equipment', () => { expect(failure('set_cover_position', { entity_id: 'climate.salon', position: 50 })).toContain('volet'); expect(failure('media_command', { entity_id: 'cover.volet_salon', command: 'play' })).toContain('enceinte'); });
  it('clamps a setpoint to what a household thermostat accepts', () => { expect(plan('set_temperature', { entity_id: 'climate.salon', temperature: 21.5 })).toMatchObject({ service: 'set_temperature', data: { temperature: 21.5 } }); const hot = plan('set_temperature', { entity_id: 'climate.salon', temperature: 45 }); expect(hot.data).toEqual({ temperature: 30 }); expect(hot.confirmation).toContain('ramenée'); expect(plan('set_temperature', { entity_id: 'climate.salon', temperature: '19' }).data).toEqual({ temperature: 19 }); expect(failure('set_temperature', { entity_id: 'climate.salon', temperature: 'chaud' })).toBe('Température invalide.'); });
  it('sends the shutter extremes through open and close rather than a position', () => { expect(plan('set_cover_position', { entity_id: 'cover.volet_salon', position: 0 }).service).toBe('close_cover'); expect(plan('set_cover_position', { entity_id: 'cover.volet_salon', position: 100 }).service).toBe('open_cover'); expect(plan('set_cover_position', { entity_id: 'cover.volet_salon', position: 143 }).service).toBe('open_cover'); expect(plan('set_cover_position', { entity_id: 'cover.volet_salon', position: 42.4 })).toMatchObject({ service: 'set_cover_position', data: { position: 42 } }); });
  it('maps the media commands and expresses the volume as Home Assistant wants it', () => { expect(plan('media_command', { entity_id: 'media_player.salon', command: 'pause' }).service).toBe('media_pause'); expect(plan('media_command', { entity_id: 'media_player.salon', command: 'next' }).service).toBe('media_next_track'); expect(plan('media_command', { entity_id: 'media_player.salon', command: 'volume', level: 40 })).toMatchObject({ service: 'volume_set', data: { volume_level: 0.4 } }); expect(failure('media_command', { entity_id: 'media_player.salon', command: 'volume' })).toContain('volume manquant'); expect(failure('media_command', { entity_id: 'media_player.salon', command: 'danser' })).toContain('Commande inconnue'); });
  it('triggers automations and turns scripts on', () => { expect(plan('run_automation', { entity_id: 'automation.volets_bas' })).toMatchObject({ domain: 'automation', service: 'trigger' }); expect(plan('run_automation', { entity_id: 'script.bonne_nuit' })).toMatchObject({ domain: 'script', service: 'turn_on' }); });
  it('reports an unknown tool instead of guessing a service', () => { expect(failure('lancer_les_missiles', { entity_id: 'climate.salon' })).toContain('Outil inconnu'); expect(failure('set_hvac_mode', { entity_id: 'climate.salon', mode: 'turbo' })).toContain('Mode inconnu'); expect(plan('set_hvac_mode', { entity_id: 'climate.salon', mode: 'off' })).toMatchObject({ service: 'set_hvac_mode', data: { hvac_mode: 'off' } }); });
});
