import { useEffect, useMemo, useState } from 'react';
import { Flame, Power, Thermometer } from 'lucide-react';
import { getHomeAssistantClient } from '../../hooks/useHomeAssistant';
import { useAppStore } from '../../stores/appStore';
import { useEntityName } from '../../hooks/useEntityName';
import type { HassEntity } from '../../types/homeAssistant';
import { selectedIds } from '../../utils/dashboard';
import { degreeUnit, numberState, temperature, unavailable } from '../../utils/entities';
export function HeatingPage() { const climateSelections = useAppStore(s => s.dashboard?.climateEntities); const entities = useAppStore(s => s.entities); const showUnavailable = useAppStore(s => s.preferences.showUnavailable); const ids = useMemo(() => selectedIds(climateSelections).filter(id => showUnavailable || !unavailable(entities[id])), [climateSelections, entities, showUnavailable]); const demo = useAppStore(s => s.demo); const update = useAppStore(s => s.updateEntity); const notify = useAppStore(s => s.notify); const setPage = useAppStore(s => s.setPage); const name = useEntityName(); return <section className="page heating-page"><header className="page-heading"><p className="eyebrow">Climat intérieur</p><h1>La juste<br /><em>chaleur.</em></h1></header><div className="climate-list">{ids.map(id => <ClimateControl key={id} entity={entities[id]} name={name(entities[id] ?? id)} demo={demo} update={update} notify={notify} />)}</div>{ids.length === 0 && <div className="empty-state"><p>Aucun chauffage n’est encore sélectionné.</p><button onClick={() => setPage('settings')}>Sélectionner mes chauffages</button></div>}</section>; }
type Props = { entity?: HassEntity; name: string; demo: boolean; update: ReturnType<typeof useAppStore.getState>['updateEntity']; notify: ReturnType<typeof useAppStore.getState>['notify'] };
function ClimateControl({ entity, ...props }: Props) { if (!entity || unavailable(entity)) return <article className="climate-control unavailable"><span>Thermostat indisponible</span></article>; return <ActiveClimateControl entity={entity} {...props} />; }
function ActiveClimateControl({ entity, name, demo, update, notify }: Props & { entity: HassEntity }) { const current = numberState({ ...entity, state: String(entity.attributes.current_temperature ?? entity.state) }); const rawTarget = Number(entity.attributes.temperature); const target = Number.isFinite(rawTarget) ? rawTarget : 20; const [draft, setDraft] = useState(target); useEffect(() => setDraft(target), [target]); const setTemperature = async (value: number) => { setDraft(value); try { if (demo) update({ ...entity, attributes: { ...entity.attributes, temperature: value } }); else await getHomeAssistantClient()?.callService('climate', 'set_temperature', { temperature: value }, { entity_id: entity.entity_id }); notify({ kind: 'success', text: `Consigne réglée à ${value.toFixed(1)}°` }); } catch { notify({ kind: 'error', text: 'La consigne n’a pas pu être envoyée.' }); } }; const active = entity.state !== 'off'; const min = Number(entity.attributes.min_temp); const max = Number(entity.attributes.max_temp); return <article className="climate-control"><div className="climate-top"><div><p>{name}</p><span className={entity.attributes.hvac_action === 'heating' ? 'heating-active' : ''}>{entity.attributes.hvac_action === 'heating' ? <><Flame size={14} /> Chauffe</> : active ? 'En régulation' : 'Mode inconnu'}</span></div><button className="icon-button" aria-label="Allumer ou éteindre" onClick={async () => { try { if (demo) update({ ...entity, state: active ? 'off' : 'heat' }); else await getHomeAssistantClient()?.callService('climate', active ? 'turn_off' : 'turn_on', {}, { entity_id: entity.entity_id }); } catch { notify({ kind: 'error', text: 'Commande de chauffage refusée.' }); } }}><Power size={17} /></button></div><div className="climate-current"><Thermometer size={17} /><b>{temperature(current, degreeUnit(entity))}</b><small>mesurée</small></div><div className="temperature-scale"><div><span>Consigne</span><output>{draft.toFixed(1)}°</output></div><button aria-label="Diminuer la consigne" onClick={() => void setTemperature(Math.max(Number.isFinite(min) ? min : 7, draft - .5))}>−</button><input aria-label="Consigne" type="range" min={Number.isFinite(min) ? min : 7} max={Number.isFinite(max) ? max : 30} step="0.5" value={draft} onChange={e => setDraft(Number(e.target.value))} onPointerUp={() => void setTemperature(draft)} /><button aria-label="Augmenter la consigne" onClick={() => void setTemperature(Math.min(Number.isFinite(max) ? max : 30, draft + .5))}>+</button></div></article>; }
