import type { HassEntity } from '../../types/homeAssistant';
export const demoEntities: HassEntity[] = [
  { entity_id: 'weather.maison', state: 'partlycloudy', attributes: { friendly_name: 'Météo de la maison', temperature: 21, temperature_unit: '°C', humidity: 64, wind_speed: 14, wind_bearing: 230, forecast: [{ templow: 14, temperature: 24 }] }, last_changed: new Date().toISOString(), last_updated: new Date().toISOString() },
  { entity_id: 'sensor.terrasse_temperature', state: '21.4', attributes: { friendly_name: 'Température extérieure', unit_of_measurement: '°C', device_class: 'temperature' }, last_changed: '', last_updated: '' },
  { entity_id: 'sensor.terrasse_humidity', state: '64', attributes: { friendly_name: 'Humidité extérieure', unit_of_measurement: '%', device_class: 'humidity' }, last_changed: '', last_updated: '' },
  { entity_id: 'sensor.uv', state: '4.1', attributes: { friendly_name: 'Indice UV', unit_of_measurement: 'UV' }, last_changed: '', last_updated: '' },
  { entity_id: 'sun.sun', state: 'above_horizon', attributes: { friendly_name: 'Soleil', next_setting: new Date(Date.now() + 1000 * 60 * 60 * 4).toISOString(), next_rising: new Date(Date.now() + 1000 * 60 * 60 * 14).toISOString() }, last_changed: '', last_updated: '' },
  { entity_id: 'sensor.tempo_aujourdhui', state: 'bleu', attributes: { friendly_name: 'Tempo aujourd’hui' }, last_changed: '', last_updated: '' },
  { entity_id: 'sensor.tempo_demain', state: 'blanc', attributes: { friendly_name: 'Tempo demain' }, last_changed: '', last_updated: '' },
  ...[['salon', 'Salon', '20.8'], ['cuisine', 'Cuisine', '21.4'], ['chambre', 'Chambre', '19.2'], ['bureau', 'Bureau', '20.1']].map(([id, name, value]) => ({ entity_id: `sensor.${id}_temperature`, state: value, attributes: { friendly_name: `Température ${name}`, unit_of_measurement: '°C', device_class: 'temperature' }, last_changed: '', last_updated: '' })),
  { entity_id: 'climate.salon', state: 'heat', attributes: { friendly_name: 'Salon', current_temperature: 20.8, temperature: 21.5, min_temp: 7, max_temp: 28, hvac_modes: ['off', 'heat', 'auto'], hvac_action: 'heating', supported_features: 17 }, last_changed: '', last_updated: '' },
  { entity_id: 'climate.chambre', state: 'auto', attributes: { friendly_name: 'Chambre', current_temperature: 19.2, temperature: 19.5, min_temp: 7, max_temp: 28, hvac_modes: ['off', 'heat', 'auto'], hvac_action: 'idle', preset_modes: ['comfort', 'eco'], supported_features: 17 }, last_changed: '', last_updated: '' },
  ...[['salon', 'Salon', '25'], ['cuisine', 'Cuisine', '100'], ['chambre', 'Chambre', '0']].map(([id, name, pos]) => ({ entity_id: `cover.volet_${id}`, state: pos === '0' ? 'closed' : 'open', attributes: { friendly_name: `Volet ${name}`, current_position: Number(pos), supported_features: 15 }, last_changed: '', last_updated: '' })),
  { entity_id: 'media_player.salon', state: 'playing', attributes: { friendly_name: 'Salon', media_title: 'Teardrop', media_artist: 'Massive Attack', media_album_name: 'Mezzanine', media_position: 146, media_duration: 330, media_content_id: 'spotify:track:1', entity_picture: '', volume_level: 0.42, source: 'Spotify', supported_features: 152511 }, last_changed: '', last_updated: '' },
  { entity_id: 'update.home_assistant_core_update', state: 'on', attributes: { friendly_name: 'Home Assistant Core', installed_version: '2026.7.0', latest_version: '2026.7.3', release_url: 'https://www.home-assistant.io/blog/' }, last_changed: '', last_updated: '' },
  { entity_id: 'update.chauffage_chambre_parentale', state: 'on', attributes: { friendly_name: 'Thermostat chambre parentale', installed_version: '1.8.0', latest_version: '1.9.0' }, last_changed: '', last_updated: '' },
  { entity_id: 'automation.ouvrir_les_volets_du_bas', state: 'on', attributes: { friendly_name: 'Ouverture des volets du bas' }, last_changed: '', last_updated: '' },
  { entity_id: 'automation.ouvrir_les_volets_du_haut', state: 'on', attributes: { friendly_name: 'Ouverture des volets du haut' }, last_changed: '', last_updated: '' }
];
export const defaultMapping = { weather: 'weather.maison', outdoorTemperature: 'sensor.terrasse_temperature', outdoorHumidity: 'sensor.terrasse_humidity', uv: 'sensor.uv', sun: 'sun.sun', tempoToday: 'sensor.tempo_aujourdhui', tempoTomorrow: 'sensor.tempo_demain', temperatures: ['sensor.salon_temperature', 'sensor.cuisine_temperature', 'sensor.chambre_temperature', 'sensor.bureau_temperature'], climates: ['climate.salon', 'climate.chambre'], covers: ['cover.volet_salon', 'cover.volet_cuisine', 'cover.volet_chambre'], mediaPlayers: ['media_player.salon'] };
