import { lazy, Suspense, useEffect, useRef } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { Flame, House, Thermometer, Blinds, Music2, Settings } from 'lucide-react';
import { PageErrorBoundary } from '../components/PageErrorBoundary';
import { useAppStore } from '../stores/appStore';
import { useHomeAssistant } from '../hooks/useHomeAssistant';
import { useDemoSimulation } from '../hooks/useDemoSimulation';
import { useSpotifyCallback } from '../hooks/useSpotify';
import { Onboarding } from '../features/onboarding/Onboarding';
import { StatusPill } from '../components/StatusPill';
const HomePage = lazy(() => import('../features/home/HomePage').then(module => ({ default: module.HomePage }))); const TemperaturesPage = lazy(() => import('../features/temperatures/TemperaturesPage').then(module => ({ default: module.TemperaturesPage }))); const HeatingPage = lazy(() => import('../features/heating/HeatingPage').then(module => ({ default: module.HeatingPage }))); const CoversPage = lazy(() => import('../features/covers/CoversPage').then(module => ({ default: module.CoversPage }))); const MediaPage = lazy(() => import('../features/media/MediaPage').then(module => ({ default: module.MediaPage }))); const SettingsPage = lazy(() => import('../features/settings/SettingsPage').then(module => ({ default: module.SettingsPage })));
const pages = [{ id: 'home', label: 'Accueil', icon: House }, { id: 'temperatures', label: 'Températures', icon: Thermometer }, { id: 'heating', label: 'Chauffage', icon: Flame }, { id: 'covers', label: 'Volets', icon: Blinds }, { id: 'media', label: 'Musique', icon: Music2 }, { id: 'settings', label: 'Réglages', icon: Settings }] as const;
export function App() { const configured = useAppStore(s => s.configured); const page = useAppStore(s => s.activePage); const setPage = useAppStore(s => s.setPage); const notification = useAppStore(s => s.notification); const notify = useAppStore(s => s.notify); const theme = useAppStore(s => s.preferences.theme); const autoHomeSeconds = useAppStore(s => s.preferences.autoHomeSeconds); const startupPage = useAppStore(s => s.preferences.startupPage); const content = useRef<HTMLElement>(null); useHomeAssistant(); useDemoSimulation(); useSpotifyCallback(); useEffect(() => { const media = window.matchMedia('(prefers-color-scheme: light)'); const apply = () => { document.documentElement.dataset.theme = theme === 'auto' ? (media.matches ? 'light' : 'dark') : theme; }; apply(); media.addEventListener('change', apply); return () => media.removeEventListener('change', apply); }, [theme]); const boot = useRef(false); useEffect(() => { if (boot.current) return; boot.current = true; setPage(startupPage); }, [setPage, startupPage]); useEffect(() => { content.current?.scrollTo({ top: 0 }); }, [page]); useEffect(() => { if (!notification) return; const id = window.setTimeout(() => notify(undefined), 3500); return () => window.clearTimeout(id); }, [notification, notify]); useEffect(() => { if (!configured || page === 'home' || !autoHomeSeconds) return; let timeout = window.setTimeout(() => setPage('home'), autoHomeSeconds * 1000); const reset = () => { window.clearTimeout(timeout); timeout = window.setTimeout(() => setPage('home'), autoHomeSeconds * 1000); }; window.addEventListener('pointerdown', reset, { passive: true }); window.addEventListener('keydown', reset); return () => { window.clearTimeout(timeout); window.removeEventListener('pointerdown', reset); window.removeEventListener('keydown', reset); }; }, [autoHomeSeconds, configured, page, setPage]); if (!configured) return <Onboarding />; const Page = { home: HomePage, temperatures: TemperaturesPage, heating: HeatingPage, covers: CoversPage, media: MediaPage, settings: SettingsPage }[page]; return <div className="app-shell"><aside className="rail"><div className="brand">S</div><nav aria-label="Navigation principale">{pages.map(item => { const Icon = item.icon; return <button key={item.id} className={page === item.id ? 'active' : ''} onClick={() => setPage(item.id)} aria-label={item.label}><Icon size={22} strokeWidth={1.8} /><span>{item.label}</span></button>; })}</nav><StatusPill /></aside><main className="content" ref={content}><AnimatePresence mode="wait"><motion.div key={page} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -5 }} transition={{ duration: .24 }}><PageErrorBoundary><Suspense fallback={<div className="page-loading">La maison se dessine…</div>}><Page /></Suspense></PageErrorBoundary></motion.div></AnimatePresence></main>{notification && <div className={`toast ${notification.kind}`} role="status" aria-live="polite">{notification.text}</div>}</div>; }
