import { useState } from 'react';
import { ArrowRight, Check, ChevronLeft, FlaskConical, KeyRound, LoaderCircle, Sparkles, Wifi } from 'lucide-react';
import { HomeAssistantClient } from '../../services/home-assistant/client';
import { discoverCandidates } from '../../services/home-assistant/normalize';
import { useAppStore } from '../../stores/appStore';
import { normalizeEntityIds } from '../../utils/dashboard';
import type { EntityMapping, HassConfig, HassEntity } from '../../types/homeAssistant';

const fields: { key: keyof EntityMapping; label: string; purpose: Parameters<typeof discoverCandidates>[1]; multiple?: boolean }[] = [
  { key: 'weather', label: 'Météo', purpose: 'weather' }, { key: 'outdoorTemperature', label: 'Température extérieure', purpose: 'outdoorTemperature' }, { key: 'outdoorHumidity', label: 'Humidité extérieure', purpose: 'outdoorHumidity' }, { key: 'uv', label: 'Indice UV', purpose: 'uv' }, { key: 'tempoToday', label: 'Tempo aujourd’hui', purpose: 'tempoToday' }, { key: 'tempoTomorrow', label: 'Tempo demain', purpose: 'tempoToday' }, { key: 'temperatures', label: 'Températures des pièces', purpose: 'temperatures', multiple: true }, { key: 'climates', label: 'Chauffage', purpose: 'climates', multiple: true }, { key: 'covers', label: 'Volets', purpose: 'covers', multiple: true }, { key: 'mediaPlayers', label: 'Musique', purpose: 'mediaPlayers', multiple: true }
];
export function Onboarding() {
  const [step, setStep] = useState(1); const [config, setConfig] = useState<HassConfig>({ homeName: 'La maison', url: '', token: '' }); const [entities, setEntities] = useState<HassEntity[]>([]); const [mapping, setMapping] = useState<EntityMapping>({}); const [diagnostic, setDiagnostic] = useState(''); const [testing, setTesting] = useState(false);
  const complete = useAppStore(s => s.completeSetup); const setStoreEntities = useAppStore(s => s.setEntities); const setStoreMapping = useAppStore(s => s.setMapping);
  async function test() { setTesting(true); setDiagnostic('Connexion en cours…'); const client = new HomeAssistantClient(config); const unsubscribe = client.onStatus(async (status, detail) => { if (status === 'connected') { try { const all = await client.getStates(); setEntities(all); setDiagnostic(`${all.length} entités découvertes. Connexion validée.`); client.disconnect(); } catch { setDiagnostic('Connecté, mais les états restent inaccessibles.'); } } else if (status === 'auth_error' || status === 'error') { setDiagnostic(detail ?? 'Connexion impossible.'); setTesting(false); } }); client.connect(); window.setTimeout(() => { unsubscribe(); client.disconnect(); setTesting(false); }, 10_000); }
  function choose(key: keyof EntityMapping, value: string) { setMapping(previous => ({ ...previous, [key]: value || undefined })); }
  /** Multi-valued mappings keep every pick: tapping an entity adds or removes it, preserving the selection order. */
  function toggle(key: keyof EntityMapping, entityId: string) { setMapping(previous => { const current = normalizeEntityIds(previous[key]); return { ...previous, [key]: current.includes(entityId) ? current.filter(id => id !== entityId) : [...current, entityId] }; }); }
  function finish() { complete(config, false); setStoreEntities(entities); setStoreMapping(mapping); }
  return <main className="onboarding"><section className="onboarding-intro"><div className="eyebrow"><Sparkles size={16} /> Domoryx</div><h1>Votre maison,<br /><em>en clair.</em></h1><p>Une présence douce sur le mur. Connectée à Home Assistant, dessinée autour de ce qui compte vraiment.</p><div className="steps"><span className={step >= 1 ? 'current' : ''}>01 Connexion</span><span className={step >= 2 ? 'current' : ''}>02 Découverte</span><span className={step >= 3 ? 'current' : ''}>03 Sélection</span></div></section><section className="onboarding-panel">
    {step === 1 && <><div className="panel-icon"><Wifi /></div><h2>Ouvrons la porte</h2><p>Vos identifiants restent dans ce navigateur, uniquement sur cet appareil.</p><label>Nom de la maison<input value={config.homeName} onChange={e => setConfig({ ...config, homeName: e.target.value })} placeholder="La maison" /></label><label>URL Home Assistant<input value={config.url} onChange={e => setConfig({ ...config, url: e.target.value })} placeholder="https://homeassistant.local:8123" inputMode="url" /></label><label>Jeton d’accès longue durée <KeyRound size={14} /><input value={config.token} onChange={e => setConfig({ ...config, token: e.target.value })} placeholder="••••••••••••••••" type="password" autoComplete="off" /></label><div className="diagnostic" aria-live="polite">{diagnostic}</div><div className="actions"><button className="ghost" onClick={() => complete(undefined, true)}><FlaskConical size={17} /> Explorer la démo</button><button className="primary" disabled={!config.url || !config.token || testing} onClick={async () => { await test(); setStep(2); }}>{testing && <LoaderCircle className="spin" size={17} />} Tester et continuer <ArrowRight size={17} /></button></div></>}
    {step === 2 && <><div className="panel-icon"><Sparkles /></div><h2>Ce que nous avons trouvé</h2><p>{entities.length ? `${entities.length} entités sont disponibles. Domoryx propose maintenant les équipements les plus pertinents.` : 'Testez votre connexion pour découvrir les équipements.'}</p><div className="discovery-summary">{['weather', 'climate', 'cover', 'media_player', 'sensor'].map(domain => <span key={domain}>{entities.filter(e => e.entity_id.startsWith(`${domain}.`)).length} {domain}</span>)}</div><div className="actions"><button className="ghost" onClick={() => setStep(1)}><ChevronLeft size={17} /> Retour</button><button className="primary" disabled={!entities.length} onClick={() => setStep(3)}>Choisir l’essentiel <ArrowRight size={17} /></button></div></>}
    {step === 3 && <><div className="panel-icon"><Check /></div><h2>Composer votre quotidien</h2><p>Chaque choix est facultatif. Vous pourrez les modifier à tout moment.</p><div className="mapping-list">{fields.map(field => { const candidates = discoverCandidates(entities, field.purpose).slice(0, field.multiple ? 40 : 6); const label = (entity: HassEntity) => String(entity.attributes.friendly_name ?? entity.entity_id);
      if (field.multiple) { const chosen = normalizeEntityIds(mapping[field.key]); return <div className="mapping-field" key={field.key}><span>{field.label}<small>{chosen.length ? `${chosen.length} sélectionné${chosen.length > 1 ? 's' : ''}` : 'Aucun'}</small></span>{candidates.length ? <div className="chip-list" role="group" aria-label={field.label}>{candidates.map(candidate => { const entityId = candidate.entity.entity_id; const active = chosen.includes(entityId); return <button type="button" key={entityId} title={entityId} className={active ? 'chip active' : 'chip'} aria-pressed={active} onClick={() => toggle(field.key, entityId)}>{active && <Check size={13} />}{label(candidate.entity)}</button>; })}</div> : <small className="muted">Aucune entité correspondante.</small>}</div>; }
      const selected = mapping[field.key]; return <label key={field.key}><span>{field.label}</span><select value={typeof selected === 'string' ? selected : ''} onChange={e => choose(field.key, e.target.value)}><option value="">Ne pas afficher</option>{candidates.map(candidate => <option key={candidate.entity.entity_id} value={candidate.entity.entity_id}>{label(candidate.entity)} · {candidate.entity.state}</option>)}</select></label>; })}</div><div className="actions"><button className="ghost" onClick={() => setStep(2)}><ChevronLeft size={17} /> Retour</button><button className="primary" onClick={finish}>Entrer dans la maison <ArrowRight size={17} /></button></div></>}
  </section></main>;
}
