import { create } from 'zustand';
import { createJSONStorage, persist } from 'zustand/middleware';
import type { AppPreferences, ConnectionStatus, DashboardEntityConfig, EntityLabels, EntityMapping, HassConfig, HassEntity, HassRegistries, Page, RoomConfig, SpotifyConfig } from '../types/homeAssistant';
import { defaultMapping, demoEntities } from '../services/home-assistant/demo';
import { defaultPreferences, migrateConfig } from './config';
import { dashboardFromMapping } from '../utils/dashboard';

type AppStore = { configured: boolean; demo: boolean; config?: HassConfig; entities: Record<string, HassEntity>; mapping: EntityMapping; dashboard: DashboardEntityConfig; labels: EntityLabels; spotify: SpotifyConfig; registries?: HassRegistries; rooms: RoomConfig[]; preferences: AppPreferences; activePage: Page; connection: ConnectionStatus; connectionDetail?: string; lastSync?: string; notification?: { kind: 'success' | 'error'; text: string }; completeSetup: (config?: HassConfig, demo?: boolean) => void; setEntities: (entities: HassEntity[]) => void; updateEntity: (entity: HassEntity) => void; setMapping: (mapping: EntityMapping) => void; setDashboard: (dashboard: DashboardEntityConfig) => void; setLabel: (entityId: string, label: string) => void; setSpotify: (changes: Partial<SpotifyConfig>) => void; setRegistries: (registries: HassRegistries) => void; setRooms: (rooms: RoomConfig[]) => void; setConnection: (status: ConnectionStatus, detail?: string) => void; setPage: (page: Page) => void; setPreferences: (preferences: Partial<AppPreferences>) => void; notify: (notification?: AppStore['notification']) => void; reset: () => void };
const entitiesToRecord = (entities: HassEntity[]) => Object.fromEntries(entities.map(entity => [entity.entity_id, entity]));
const json = createJSONStorage<Partial<AppStore>>(() => localStorage)!; let lastWrite: string | undefined;
/** Home Assistant pushes an event per entity change: only touch localStorage when the persisted slice really changed. */
const storage: typeof json = { ...json, setItem: (name, value) => { const payload = JSON.stringify(value); if (payload === lastWrite) return; lastWrite = payload; json.setItem(name, value); }, removeItem: name => { lastWrite = undefined; json.removeItem(name); } };
export const useAppStore = create<AppStore>()(persist((set) => ({
  configured: false, demo: false, entities: {}, mapping: {}, dashboard: dashboardFromMapping(), labels: {}, spotify: { clientId: import.meta.env.VITE_SPOTIFY_CLIENT_ID }, rooms: [], preferences: defaultPreferences, activePage: 'home', connection: 'idle',
  completeSetup: (config, demo = false) => { const mapping = demo ? defaultMapping : {}; const dashboard = dashboardFromMapping(mapping); if (demo) { dashboard.updateEntities = [{ entityId: 'update.home_assistant_core_update', enabled: true, order: 0 }, { entityId: 'update.chauffage_chambre_parentale', enabled: true, order: 1 }]; dashboard.automationLower = { entityId: 'automation.ouvrir_les_volets_du_bas', enabled: true, order: 0 }; dashboard.automationUpper = { entityId: 'automation.ouvrir_les_volets_du_haut', enabled: true, order: 0 }; } return set({ configured: true, demo, config, entities: demo ? entitiesToRecord(demoEntities) : {}, mapping, dashboard, rooms: demo ? [{ id: 'salon', name: 'Salon', temperature: 'sensor.salon_temperature', climate: 'climate.salon', cover: 'cover.volet_salon', order: 0 }, { id: 'cuisine', name: 'Cuisine', temperature: 'sensor.cuisine_temperature', cover: 'cover.volet_cuisine', order: 1 }, { id: 'chambre', name: 'Chambre', temperature: 'sensor.chambre_temperature', cover: 'cover.volet_chambre', order: 2 }, { id: 'bureau', name: 'Bureau', temperature: 'sensor.bureau_temperature', order: 3 }] : [] }); },
  setEntities: entities => set({ entities: entitiesToRecord(entities), lastSync: new Date().toISOString() }), updateEntity: entity => set(state => ({ entities: { ...state.entities, [entity.entity_id]: entity }, lastSync: new Date().toISOString() })), setMapping: mapping => set({ mapping, dashboard: dashboardFromMapping(mapping) }), setDashboard: dashboard => set({ dashboard }), setLabel: (entityId, label) => set(state => { const labels = { ...state.labels }; if (label.trim()) labels[entityId] = label.trim(); else delete labels[entityId]; return { labels }; }), setSpotify: changes => set(state => ({ spotify: { ...state.spotify, ...changes } })), setRegistries: registries => set({ registries }), setRooms: rooms => set({ rooms }), setConnection: (connection, connectionDetail) => set({ connection, connectionDetail }), setPage: activePage => set({ activePage }), setPreferences: changes => set(state => ({ preferences: { ...state.preferences, ...changes } })), notify: notification => set({ notification }),
  reset: () => set({ configured: false, demo: false, config: undefined, entities: {}, mapping: {}, dashboard: dashboardFromMapping(), labels: {}, spotify: { clientId: import.meta.env.VITE_SPOTIFY_CLIENT_ID }, rooms: [], activePage: 'home', connection: 'idle', connectionDetail: undefined, lastSync: undefined })
}), { name: 'sillage-config-v1', version: 4, storage, migrate: persisted => migrateConfig(persisted) as never, partialize: state => ({ configured: state.configured, demo: state.demo, config: state.config, mapping: state.mapping, dashboard: state.dashboard, labels: state.labels, spotify: state.spotify, rooms: state.rooms, preferences: state.preferences, activePage: state.activePage }) }));
