import { afterEach, describe, expect, it, vi } from 'vitest';
import { OpenRouterClient, OpenRouterError, toolArguments } from './client';
const credentials = () => ({ apiKey: 'sk-test', model: 'deepseek/deepseek-chat' });
const respond = (body: unknown, status = 200) => vi.fn().mockResolvedValue({ ok: status < 400, status, json: async () => body } as Response);
afterEach(() => vi.unstubAllGlobals());
describe('OpenRouter client', () => {
  it('sends the configured model and returns the answer', async () => { const fetcher = respond({ choices: [{ message: { content: '  Il fait 20°C.  ' } }] }); vi.stubGlobal('fetch', fetcher); const reply = await new OpenRouterClient(credentials).chat([{ role: 'user', content: 'Quelle température ?' }]); expect(reply.content).toBe('Il fait 20°C.'); expect(reply.toolCalls).toEqual([]); const body = JSON.parse(String((fetcher.mock.calls[0]![1] as RequestInit).body)) as { model: string; tools?: unknown }; expect(body.model).toBe('deepseek/deepseek-chat'); expect(body.tools).toBeUndefined(); });
  it('keeps the tool calls and tolerates a null content', async () => { vi.stubGlobal('fetch', respond({ choices: [{ message: { content: null, tool_calls: [{ id: '1', type: 'function', function: { name: 'set_temperature', arguments: '{"entity_id":"climate.salon","temperature":21}' } }, { id: '2', type: 'function', function: {} }] } }] })); const reply = await new OpenRouterClient(credentials).chat([{ role: 'user', content: 'Monte à 21' }], [{ type: 'function', function: { name: 'set_temperature', description: '', parameters: {} } }]); expect(reply.content).toBe(''); expect(reply.toolCalls).toHaveLength(1); expect(toolArguments(reply.toolCalls[0]!)).toEqual({ entity_id: 'climate.salon', temperature: 21 }); });
  it('translates the transport and credential failures', async () => { vi.stubGlobal('fetch', respond({ error: { message: 'No auth credentials found' } }, 401)); await expect(new OpenRouterClient(credentials).chat([])).rejects.toThrow('La clé OpenRouter a été refusée.'); vi.stubGlobal('fetch', vi.fn().mockRejectedValue(new TypeError('Failed to fetch'))); await expect(new OpenRouterClient(credentials).chat([])).rejects.toMatchObject({ status: 0, message: 'OpenRouter est injoignable.' }); await expect(new OpenRouterClient(() => ({ apiKey: '', model: 'x' })).chat([])).rejects.toBeInstanceOf(OpenRouterError); });
  it('refuses an answer without a choice rather than pretending the model stayed silent', async () => { vi.stubGlobal('fetch', respond({ error: { message: 'Provider returned error' } })); await expect(new OpenRouterClient(credentials).chat([])).rejects.toThrow('Provider returned error'); });
  it('never throws on malformed tool arguments', () => { expect(toolArguments({ id: '1', type: 'function', function: { name: 'x', arguments: 'oops' } })).toEqual({}); expect(toolArguments({ id: '1', type: 'function', function: { name: 'x', arguments: '[1,2]' } })).toEqual({}); });
});
