import { useEffect, useMemo, useState } from 'react';
import { ChevronDown, ChevronUp, Pause, SlidersHorizontal } from 'lucide-react';
import { useAppStore } from '../../stores/appStore';
import { getHomeAssistantClient } from '../../hooks/useHomeAssistant';
import { useEntityName } from '../../hooks/useEntityName';
import { unavailable } from '../../utils/entities';
import { selectedIds } from '../../utils/dashboard';
import type { HassEntity } from '../../types/homeAssistant';
export function CoversPage() { const coverSelections = useAppStore(s => s.dashboard?.coverEntities); const entities = useAppStore(s => s.entities); const showUnavailable = useAppStore(s => s.preferences.showUnavailable); const ids = useMemo(() => selectedIds(coverSelections).filter(id => showUnavailable || !unavailable(entities[id])), [coverSelections, entities, showUnavailable]); const [page, setPage] = useState(0); const demo = useAppStore(s => s.demo); const update = useAppStore(s => s.updateEntity); const confirm = useAppStore(s => s.preferences.confirmGlobalActions); const notify = useAppStore(s => s.notify); const name = useEntityName(); const pageSize = 4; const pageCount = Math.max(1, Math.ceil(ids.length / pageSize)); const start = Math.min(page, pageCount - 1) * pageSize; const visibleIds = ids.slice(start, start + pageSize); const command = async (id: string | string[], service: string, position?: number) => { try { if (demo) (Array.isArray(id) ? id : [id]).forEach(entityId => { const entity = entities[entityId]; if (entity) update({ ...entity, state: service === 'close_cover' ? 'closed' : 'open', attributes: { ...entity.attributes, current_position: position ?? (service === 'close_cover' ? 0 : 100) } }); }); else await getHomeAssistantClient()?.callService('cover', service, position === undefined ? {} : { position }, { entity_id: id }); notify({ kind: 'success', text: 'Commande envoyée.' }); } catch { notify({ kind: 'error', text: 'La commande a été refusée.' }); } }; const global = (service: string) => { if (!confirm || window.confirm('Appliquer cette action à tous les volets sélectionnés ?')) void command(ids, service); }; return <section className="page covers-page"><header className="page-heading"><p className="eyebrow">Lumière & intimité</p><h1>Les volets,<br /><em>au bon rythme.</em></h1><div className="global-actions"><button onClick={() => global('open_cover')}>Tout ouvrir</button><button onClick={() => global('close_cover')}>Tout fermer</button></div></header><div className="cover-list">{visibleIds.map(id => <CoverControl key={id} entity={entities[id]} name={name(entities[id] ?? id)} command={command} />)}</div>{pageCount > 1 && <div className="cover-pagination" aria-label="Pages de volets">{Array.from({ length: pageCount }, (_, index) => <button key={index} aria-label={`Page ${index + 1}`} aria-current={index === page ? 'page' : undefined} className={index === page ? 'active' : ''} onClick={() => setPage(index)} />)}</div>}{!ids.length && <p className="empty">Sélectionnez vos volets dans Réglages.</p>}</section>; }
function CoverControl({ entity, name, command }: { entity?: HassEntity; name: string; command: (id: string, service: string, position?: number) => Promise<void> }) {
  const position = Number(entity?.attributes.current_position ?? (entity?.state === 'closed' ? 0 : 100));
  /** The slider stays local while the finger moves: one service call on release instead of one per pixel. */
  const [draft, setDraft] = useState(position); useEffect(() => setDraft(position), [position]);
  const commit = () => { if (entity && draft !== position) void command(entity.entity_id, 'set_cover_position', draft); };
  return <article className="cover-control"><div><p>{name}</p><span>{unavailable(entity) ? 'Indisponible' : `${draft}% ouvert`}</span></div><div className="shutter" style={{ '--open': `${draft}%` } as React.CSSProperties}><i /><i /><i /><i /><i /></div><div className="cover-actions"><button aria-label={`Ouvrir ${name}`} title="Ouvrir" onClick={() => entity && void command(entity.entity_id, 'open_cover')}><ChevronUp size={19} /></button><button aria-label={`Fermer ${name}`} title="Fermer" onClick={() => entity && void command(entity.entity_id, 'close_cover')}><ChevronDown size={19} /></button><button aria-label={`Stopper ${name}`} title="Stopper" onClick={() => entity && void command(entity.entity_id, 'stop_cover')}><Pause size={16} /></button></div><label className="cover-range"><SlidersHorizontal size={16} /><input aria-label={`Position ${name}`} type="range" min="0" max="100" value={draft} onChange={e => setDraft(Number(e.target.value))} onPointerUp={commit} onKeyUp={commit} onBlur={commit} /></label></article>;
}
