import { useEffect, useMemo, useRef, useState } from 'react';
import { ChevronDown, ChevronUp, Pause, SlidersHorizontal } from 'lucide-react';
import { useAppStore } from '../../stores/appStore';
import { getHomeAssistantClient } from '../../hooks/useHomeAssistant';
import { useEntityName } from '../../hooks/useEntityName';
import { unavailable } from '../../utils/entities';
import { selectedIds } from '../../utils/dashboard';
import type { HassEntity } from '../../types/homeAssistant';
/** A wall display is read at a glance, never scrolled: covers are laid out in full screens you swipe through. */
const useCoversPerPage = () => { const [perPage, setPerPage] = useState(4); useEffect(() => { const narrow = window.matchMedia('(max-width:620px)'); const apply = () => setPerPage(narrow.matches ? 2 : 4); apply(); narrow.addEventListener('change', apply); return () => narrow.removeEventListener('change', apply); }, []); return perPage; };
export function CoversPage() { const coverSelections = useAppStore(s => s.dashboard?.coverEntities); const entities = useAppStore(s => s.entities); const showUnavailable = useAppStore(s => s.preferences.showUnavailable); const ids = useMemo(() => selectedIds(coverSelections).filter(id => showUnavailable || !unavailable(entities[id])), [coverSelections, entities, showUnavailable]); const [page, setPage] = useState(0); const demo = useAppStore(s => s.demo); const update = useAppStore(s => s.updateEntity); const confirm = useAppStore(s => s.preferences.confirmGlobalActions); const notify = useAppStore(s => s.notify); const name = useEntityName(); const perPage = useCoversPerPage(); const scroller = useRef<HTMLDivElement>(null); const pages = useMemo(() => Array.from({ length: Math.max(1, Math.ceil(ids.length / perPage)) }, (_, index) => ids.slice(index * perPage, index * perPage + perPage)), [ids, perPage]); useEffect(() => { if (page > pages.length - 1) { setPage(0); scroller.current?.scrollTo({ left: 0 }); } }, [page, pages.length]); const goTo = (index: number) => { setPage(index); scroller.current?.scrollTo({ left: index * (scroller.current?.clientWidth ?? 0), behavior: 'smooth' }); }; const command = async (id: string | string[], service: string, position?: number) => { try { if (demo) (Array.isArray(id) ? id : [id]).forEach(entityId => { const entity = entities[entityId]; if (entity) update({ ...entity, state: service === 'close_cover' ? 'closed' : 'open', attributes: { ...entity.attributes, current_position: position ?? (service === 'close_cover' ? 0 : 100) } }); }); else await getHomeAssistantClient()?.callService('cover', service, position === undefined ? {} : { position }, { entity_id: id }); notify({ kind: 'success', text: 'Commande envoyée.' }); } catch { notify({ kind: 'error', text: 'La commande a été refusée.' }); } }; const global = (service: string) => { if (!confirm || window.confirm('Appliquer cette action à tous les volets sélectionnés ?')) void command(ids, service); }; return <section className="page covers-page"><header className="page-heading"><div><p className="eyebrow">Lumière & intimité</p><h1>Les volets, <em>au bon rythme.</em></h1></div><div className="global-actions"><button onClick={() => global('open_cover')}>Tout ouvrir</button><button onClick={() => global('close_cover')}>Tout fermer</button></div></header>
  {ids.length ? <><div className="cover-pages" ref={scroller} onScroll={event => { const width = event.currentTarget.clientWidth; if (width) setPage(Math.round(event.currentTarget.scrollLeft / width)); }}>{pages.map((group, index) => <div className="cover-list" key={index}>{group.map(id => <CoverControl key={id} entity={entities[id]} name={name(entities[id] ?? id)} command={command} />)}</div>)}</div>
    {pages.length > 1 && <div className="cover-pagination" aria-label="Pages de volets">{pages.map((_, index) => <button key={index} aria-label={`Page ${index + 1}`} aria-current={index === page ? 'page' : undefined} className={index === page ? 'active' : ''} onClick={() => goTo(index)} />)}</div>}</> : <p className="empty">Sélectionnez vos volets dans Réglages.</p>}
</section>; }
function CoverControl({ entity, name, command }: { entity?: HassEntity; name: string; command: (id: string, service: string, position?: number) => Promise<void> }) {
  const position = Number(entity?.attributes.current_position ?? (entity?.state === 'closed' ? 0 : 100));
  /** The slider stays local while the finger moves: one service call on release instead of one per pixel. */
  const [draft, setDraft] = useState(position); useEffect(() => setDraft(position), [position]);
  const commit = () => { if (entity && draft !== position) void command(entity.entity_id, 'set_cover_position', draft); };
  const state = unavailable(entity) ? 'unavailable' : draft === 0 ? 'closed' : draft === 100 ? 'open' : 'partial';
  const label = { unavailable: 'Indisponible', closed: 'Fermé', open: 'Ouvert', partial: `Entrouvert · ${draft}%` }[state];
  return <article className="cover-control" data-state={state}><div><p>{name}</p><span className="cover-state">{label}</span></div><div className="shutter" aria-hidden style={{ '--open': `${draft}%` } as React.CSSProperties}><i /></div><div className="cover-actions"><button aria-label={`Ouvrir ${name}`} title="Ouvrir" onClick={() => entity && void command(entity.entity_id, 'open_cover')}><ChevronUp size={19} /></button><button aria-label={`Fermer ${name}`} title="Fermer" onClick={() => entity && void command(entity.entity_id, 'close_cover')}><ChevronDown size={19} /></button><button aria-label={`Stopper ${name}`} title="Stopper" onClick={() => entity && void command(entity.entity_id, 'stop_cover')}><Pause size={16} /></button></div><label className="cover-range"><SlidersHorizontal size={16} /><input aria-label={`Position ${name}`} type="range" min="0" max="100" value={draft} onChange={e => setDraft(Number(e.target.value))} onPointerUp={commit} onKeyUp={commit} onBlur={commit} /></label></article>;
}
